### ISSUE TITLE
Save and restore open modules

### ISSUE THREAD

**Issue by trixon** [dlsc-software-consulting-gmbh/WorkbenchFX#107]
I can't find any hooks to use that differs between manually closing a module and the closing that gets done on application exit.

Whats is the proper way to save and restore open modules, like a web browser?

**Comment by dlemmermann** [comment]
You can get the list of the current modules via Workbench.getOpenModules(). You would then need to persist this information and later on call Workbench.openModule().

**Comment by trixon** [comment]
Will do, thanks!
