### ISSUE TITLE
archive contains com.sun classes

### ISSUE THREAD

**Issue by wolpers** [dlsc-software-consulting-gmbh/WorkbenchFX#124]
The workbenchfx-core archive contains the **com.sun.** package, and also **com.google**.  I am not overly familiar with maven and could not see why these packages would be part of the generated archive.  The com.sun classes seem to be part of JavaFX and the bundeled version breaks my Application on MacOS.  I can only assume they are included by accident, or did you patch something?  When I find the time tonight I will exclude these classes from my build to see if things work without it.

https://repo1.maven.org/maven2/com/dlsc/workbenchfx/workbenchfx-core/11.1.0/workbenchfx-core-11.1.0.jar

**Comment by dlemmermann** [comment]
This is obsolete after the last changes made to the build process. You should no longer see those packages (at least not in the version for Java 11+).
