### ISSUE TITLE
Please provide non shaded artifact

### ISSUE THREAD

**Issue by garzy** [dlsc-software-consulting-gmbh/WorkbenchFX#139]
The current workbenchFX maven artifact is a shaded jar with all dependencies inside. This breaks my current projects' maven structure configuration (especially logging system).

I would like to exclude some incompatible dependencies or WorkbenchFX but with a shaded jar, it's impossible.

I think this is a bad practice, you shouldn't include third-party libs in your artifact as it's maybe violated license terms on some of them.

Please provide an artifact without shaded dependencies.

Thanks.

**Comment by caprica** [comment]
Also the module-info.class is not in the shaded jar, but it's in the original. This causes problems trying to use WorkbenchFX in a project that uses modules.

**Comment by trixon** [comment]
I would like to have it non shaded too.

I forked this project and changed the configuration of maven-shade-plugin.
At first I added <artifactSet><excludes><exclude>org.openjfx:*</exclude></excludes></artifactSet>
and the disabled the shading completely with <phase>none</phase>.
They both works good for me.

@dlemmermann Would any of these be accepted as a PR?

**Comment by dlemmermann** [comment]
I completely removed the shading.
