### ISSUE TITLE
Wrong image size for tiles constructed with Image

### ISSUE THREAD

**Issue by AndreasEhret** [dlsc-software-consulting-gmbh/WorkbenchFX#20]
I am trying to make the tiles icons a little more eye-catching (increase the size). Unfortunately this seems not be allowed as there is no way to set the size (or a size hint such as S, M, XL) and the WorkbenchModule.getIcon() is declared final.  

So I tried to use the WorkbenchModule constructor 

protected WorkbenchModule(String name, Image icon) 

that allows to hand over an Image and I thought that could help and so I did call this with:

  public MyModule() {
    super("Module Title", new Image(MyModule.class.getResource("java-brands.svg").toExternalForm()));

The result is, that the image is far too big in the tile and also in the tab when I open the module. 

My expectation is that the size of the image behaves at least the same as for the tiles that are constructed using the FontAwesomeIcon or MaterialDesignIcon, so that I can create tiles based on font icons as well as on images (e.g. for situations where the font icons does not provide the symbol I need).

**Comment by dlemmermann** [comment]
You could pass an ImageView with the image. On ImageView you can set fitWidth / fitHeight.
