### ISSUE TITLE
Has this issue been resolved?

### ISSUE THREAD

**Issue by JoshuaOlu** [dlsc-software-consulting-gmbh/WorkbenchFX#591]
Has this issue been resolved?

I'm also having a similar problem. Here's the error:

error: the unnamed module reads package javafx.application from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.geometry from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.stage from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.concurrent from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.print from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.animation from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.css from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.css.converter from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.scene from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.scene.transform from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.scene.text from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.scene.canvas from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.scene.image from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.scene.robot from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.scene.effect from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.scene.layout from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.scene.input from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.scene.shape from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.scene.paint from both javafx.graphics and workbenchfx.core
error: the unnamed module reads package javafx.scene.control from both javafx.controls and workbenchfx.core
error: the unnamed module reads package javafx.scene.control.cell from both javafx.controls and workbenchfx.core
error: the unnamed module reads package javafx.scene.control.skin from both javafx.controls and workbenchfx.core
error: the unnamed module reads package javafx.scene.chart from both javafx.controls and workbenchfx.core
error: the unnamed module reads package javafx.beans from both workbenchfx.core and javafx.base
error: the unnamed module reads package javafx.beans.binding from both workbenchfx.core and javafx.base
error: the unnamed module reads package javafx.beans.property from both workbenchfx.core and javafx.base
error: the unnamed module reads package javafx.beans.property.adapter from both workbenchfx.core and javafx.base
error: the unnamed module reads package javafx.beans.value from both workbenchfx.core and javafx.base
error: the unnamed module reads package javafx.collections from both workbenchfx.core and javafx.base
error: the unnamed module reads package javafx.collections.transformation from both workbenchfx.core and javafx.base
error: the unnamed module reads package javafx.event from both workbenchfx.core and javafx.base
error: the unnamed module reads package javafx.util from both workbenchfx.core and javafx.base
error: the unnamed module reads package javafx.util.converter from both workbenchfx.core and javafx.base
error: the unnamed module reads package javafx.fxml from both workbenchfx.core and javafx.fxml
error: module javafx.controlsEmpty reads package javafx.fxml from both workbenchfx.core and javafx.fxml
error: module javafx.controlsEmpty reads package javafx.beans from both workbenchfx.core and javafx.base
error: module javafx.controlsEmpty reads package javafx.beans.binding from both workbenchfx.core and javafx.base
error: module javafx.controlsEmpty reads package javafx.beans.property from both workbenchfx.core and javafx.base
error: module javafx.controlsEmpty reads package javafx.beans.property.adapter from both workbenchfx.core and javafx.base
error: module javafx.controlsEmpty reads package javafx.beans.value from both workbenchfx.core and javafx.base
error: module javafx.controlsEmpty reads package javafx.collections from both workbenchfx.core and javafx.base
error: module javafx.controlsEmpty reads package javafx.collections.transformation from both workbenchfx.core and javafx.base
error: module javafx.controlsEmpty reads package javafx.event from both workbenchfx.core and javafx.base
error: module javafx.controlsEmpty reads package javafx.util from both workbenchfx.core and javafx.base
error: module javafx.controlsEmpty reads package javafx.util.converter from both workbenchfx.core and javafx.base
error: module javafx.controlsEmpty reads package javafx.scene.chart from both workbenchfx.core and javafx.controls
error: module javafx.controlsEmpty reads package javafx.scene.control from both workbenchfx.core and javafx.controls
error: module javafx.controlsEmpty reads package javafx.scene.control.cell from both workbenchfx.core and javafx.controls
error: module javafx.controlsEmpty reads package javafx.scene.control.skin from both workbenchfx.core and javafx.controls
error: module javafx.controlsEmpty reads package javafx.animation from both workbenchfx.core and javafx.graphics
error: module javafx.controlsEmpty reads package javafx.application from both workbenchfx.core and javafx.graphics
error: module javafx.controlsEmpty reads package javafx.concurrent from both workbenchfx.core and javafx.graphics
error: module javafx.controlsEmpty reads package javafx.css from both workbenchfx.core and javafx.graphics
error: module javafx.controlsEmpty reads package javafx.css.converter from both workbenchfx.core and javafx.graphics
error: module javafx.controlsEmpty reads package javafx.geometry from both workbenchfx.core and javafx.graphics
error: module javafx.controlsEmpty reads package javafx.print from both workbenchfx.core and javafx.graphics
error: module javafx.controlsEmpty reads package javafx.scene from both workbenchfx.core and javafx.graphics
error: module javafx.controlsEmpty reads package javafx.scene.canvas from both workbenchfx.core and javafx.graphics
error: module javafx.controlsEmpty reads package javafx.scene.effect from both workbenchfx.core and javafx.graphics
error: module javafx.controlsEmpty reads package javafx.scene.image from both workbenchfx.core and javafx.graphics
error: module javafx.controlsEmpty reads package javafx.scene.input from both workbenchfx.core and javafx.graphics
error: module javafx.controlsEmpty reads package javafx.scene.layout from both workbenchfx.core and javafx.graphics
error: module javafx.controlsEmpty reads package javafx.scene.paint from both workbenchfx.core and javafx.graphics
error: module javafx.controlsEmpty reads package javafx.scene.robot from both workbenchfx.core and javafx.graphics
error: module javafx.controlsEmpty reads package javafx.scene.shape from both workbenchfx.core and javafx.graphics
error: module javafx.controlsEmpty reads package javafx.scene.text from both workbenchfx.core and javafx.graphics
error: module javafx.controlsEmpty reads package javafx.scene.transform from both workbenchfx.core and javafx.graphics
error: module javafx.controlsEmpty reads package javafx.stage from both workbenchfx.core and javafx.graphics
error: module javafx.graphicsEmpty reads package javafx.fxml from both workbenchfx.core and javafx.fxml
error: module javafx.graphicsEmpty reads package javafx.beans from both workbenchfx.core and javafx.base
error: module javafx.graphicsEmpty reads package javafx.beans.binding from both workbenchfx.core and javafx.base
error: module javafx.graphicsEmpty reads package javafx.beans.property from both workbenchfx.core and javafx.base
error: module javafx.graphicsEmpty reads package javafx.beans.property.adapter from both workbenchfx.core and javafx.base
error: module javafx.graphicsEmpty reads package javafx.beans.value from both workbenchfx.core and javafx.base
error: module javafx.graphicsEmpty reads package javafx.collections from both workbenchfx.core and javafx.base
error: module javafx.graphicsEmpty reads package javafx.collections.transformation from both workbenchfx.core and javafx.base
error: module javafx.graphicsEmpty reads package javafx.event from both workbenchfx.core and javafx.base
error: module javafx.graphicsEmpty reads package javafx.util from both workbenchfx.core and javafx.base
error: module javafx.graphicsEmpty reads package javafx.util.converter from both workbenchfx.core and javafx.base
error: module javafx.graphicsEmpty reads package javafx.scene.chart from both workbenchfx.core and javafx.controls
error: module javafx.graphicsEmpty reads package javafx.scene.control from both workbenchfx.core and javafx.controls
error: module javafx.graphicsEmpty reads package javafx.scene.control.cell from both workbenchfx.core and javafx.controls
error: module javafx.graphicsEmpty reads package javafx.scene.control.skin from both workbenchfx.core and javafx.controls
error: module javafx.graphicsEmpty reads package javafx.animation from both workbenchfx.core and javafx.graphics
error: module javafx.graphicsEmpty reads package javafx.application from both workbenchfx.core and javafx.graphics
error: module javafx.graphicsEmpty reads package javafx.concurrent from both workbenchfx.core and javafx.graphics
error: module javafx.graphicsEmpty reads package javafx.css from both workbenchfx.core and javafx.graphics
error: module javafx.graphicsEmpty reads package javafx.css.converter from both workbenchfx.core and javafx.graphics
error: module javafx.graphicsEmpty reads package javafx.geometry from both workbenchfx.core and javafx.graphics
error: module javafx.graphicsEmpty reads package javafx.print from both workbenchfx.core and javafx.graphics
error: module javafx.graphicsEmpty reads package javafx.scene from both workbenchfx.core and javafx.graphics
error: module javafx.graphicsEmpty reads package javafx.scene.canvas from both workbenchfx.core and javafx.graphics
error: module javafx.graphicsEmpty reads package javafx.scene.effect from both workbenchfx.core and javafx.graphics
error: module javafx.graphicsEmpty reads package javafx.scene.image from both workbenchfx.core and javafx.graphics
error: module javafx.graphicsEmpty reads package javafx.scene.input from both workbenchfx.core and javafx.graphics
error: module javafx.graphicsEmpty reads package javafx.scene.layout from both workbenchfx.core and javafx.graphics
error: module javafx.graphicsEmpty reads package javafx.scene.paint from both workbenchfx.core and javafx.graphics
error: module javafx.graphicsEmpty reads package javafx.scene.robot from both workbenchfx.core and javafx.graphics
error: module javafx.graphicsEmpty reads package javafx.scene.shape from both workbenchfx.core and javafx.graphics
error: module javafx.graphicsEmpty reads package javafx.scene.text from both workbenchfx.core and javafx.graphics
100 errors
only showing the first 100 errors, of 375 total; use -Xmaxerrs if you would like to see more

_Originally posted by @JoshuaOlu in https://github.com/dlsc-software-consulting-gmbh/WorkbenchFX/issues/14#issuecomment-891264062_

**Comment by JoshuaOlu** [comment]
I'm working with workbench V11.0.0 and javafx v11.0.2 Please I need a response

**Comment by dlemmermann** [comment]
yes
