### ISSUE TITLE
README.md contains inaccurate screenshots

### ISSUE THREAD

**Issue by effad** [dlsc-software-consulting-gmbh/WorkbenchFX#607]
The screenshots below "This code snippet results in the following application:" show a workbench that will require the user to create a module. It seems however that WorkbenchFX automatically creates the module, if only one module is passed into the Workbench.builder.

**Comment by effad** [comment]
Ah, reading on, I can see the single module situation is explained below... Still a bit surprising for people that work the README.md top to bottom ...

**Comment by dlemmermann** [comment]
Good enough. :-)
