### ISSUE TITLE
Open module without load it

### ISSUE THREAD

**Issue by hortegag91** [dlsc-software-consulting-gmbh/WorkbenchFX#63]
Let me say workbench its great, thanks for it!!..
Well, i have a list and need a "submodule" to edit the objects of the list
In first, i think i can create a module and just open it (without load it before), but i did it and get the error "Module has not been loaded yet"
It supose they dont clic on a module, only by the list and then clic on edit button.
Is there any way i can do that? or am i doing anything wrong?
Thanks

**Comment by martinfrancois** [comment]
Hi @hortegag91
First off, thanks for the praise! We're glad you like it!
In your use case, if you don't want to offer the possibility to edit in the same module, another way we thought of this would be to create a custom dialog (see the Readme file for details on how to do that) to edit the objects in your list. This would follow user experience best practices, as after pressing maybe a "Save" button on the dialog, the user will see the module again and may already see changed properties in the list.

Would this work for your scenario in a way that would be satisfactory? If not, please provide us with more details about what you want to achieve and why you think the way you're proposing is the best way of achieving it, so we can better understand your use case!

**Comment by hortegag91** [comment]
I was thinking i can show the edit on a CustomOverlay.
I'll try it, thanks!

**Comment by martinfrancois** [comment]
Sure, you can also just use a custom dialog, that should be even easier!
Feel free to reopen it, if you still have open questions.
