### ISSUE TITLE
Why are openjfx libs included in the workbenchfx jar file?

### ISSUE THREAD

**Issue by countfloyd** [dlsc-software-consulting-gmbh/WorkbenchFX#76]
This makes it difficult to use other versions of jfx with workbenchfx. Also, I got NPE during css parsing for some reason. I had to build a new version of workbenchfx without the openjfx classes and then it works great!

**Comment by martinfrancois** [comment]
Thanks for reporting!
I just released version `11.0.3` which has them removed. Can you please try again and close this issue, should it be fixed now? @countfloyd

**Comment by countfloyd** [comment]
Yes, thank you!
