### ISSUE TITLE
Constructing Activity Link between 2 Activities

### ISSUE THREAD

**Issue by Bwjx94** [dlsc-software-consulting-gmbh/WorkbenchFX#78]
Hi

In the documentation (Under 4.3 Activity Link), the code for linking 2 activities is:
GanttChart.getLinks().add(myLink);

However, I'm still not sure about how the link "myLink" is created. Do you have any code snippets on how myLink can be created. Thanks.

**Comment by dlemmermann** [comment]
Wrong framework. You are talking about FlexGanttFX, right? Please visit the forum at disc.com and post your questions there.
