### ISSUE TITLE
Extract Dialogs to separate project?

### ISSUE THREAD

**Issue by cardosso** [dlsc-software-consulting-gmbh/WorkbenchFX#82]
Is this something that you would consider doing? I think your dialogs look just so much better than the JFX ones that they should probably be used by everyone else instead of those.

So for projects not using WorkbenchFX having the possibility to simply include the dialogs as a separate dependency (DialogsFX?) would be perfect.

**Comment by dlemmermann** [comment]
Please have a look at GemsFX. It provides a dialog framework.
