### ISSUE TITLE
Module-internal Windowing system

### ISSUE THREAD

**Issue by trixon** [dlsc-software-consulting-gmbh/WorkbenchFX#96]
While moving from Java 8 to 11+ I decided to replace the NetBeans Platform MainWindow (Frame) with WorkbenchFX in order to make the application a more "FX" like.
Until now, it has been a hybrid one where Windows and Dialogs was Swing and their content was JavaFX. What can I say, mixing toolkits isn't that fun...

But working with WorbenchFX is :) Thank you!

There is one thing that I miss really much though and that is blocking me at the moment, and that is the [NetBeans Window System](https://ui.netbeans.org/docs/ui/ws/ws_spec.html) 

The original NetBeans Window System based application looks like
![2019-10-10-175314_1311x841_scrot](https://user-images.githubusercontent.com/153314/66585687-92f2aa80-eb87-11e9-8ce4-6468046dc2e1.png)

and I'm making some progress with WorkbenchFX
![2019-10-10-175438_1316x844_scrot](https://user-images.githubusercontent.com/153314/66585741-ae5db580-eb87-11e9-98a7-262d2ba34c82.png)

so, the challenge now is to have internal windows like this mockup
![2019-10-10-175652_1332x844_scrot](https://user-images.githubusercontent.com/153314/66585777-bfa6c200-eb87-11e9-9a96-7f90843a4a03.png)

Have you any plans for adding this to WorkbenchFX?

Once again, thank you for a really nice piece of work!

Edit: Fixed URL & some typos

**Comment by dlemmermann** [comment]
No, this feature is not planned. I think it is too specific for WorkbenchFX.

**Comment by trixon** [comment]
I fully understand.
